name: ipyp5_docs
channels:
- conda-forge
- defaults
dependencies:
- nodejs
- jupyter_sphinx
- nbformat
- nbsphinx
- notebook>=4.2
- python=3.6
- sphinx>=1.5
- sphinx_rtd_theme
- tornado
- python-dateutil
- recommonmark
